// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionEffect } from "./ActionEffect";
import type { ActionTarget } from "./ActionTarget";

export type Action = { target: ActionTarget, effect: ActionEffect, };
