// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardCell } from "./BoardCell";
import type { BoardId } from "./BoardId";
import type { UserId } from "./UserId";

export type Board = { id: BoardId, users_connected: Array<UserId>, cells: [BoardCell, BoardCell, BoardCell, BoardCell, BoardCell, BoardCell, BoardCell, BoardCell, BoardCell, BoardCell], };
