// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardAction } from "./CardAction";
import type { CardTarget } from "./CardTarget";

export type Card = { target: CardTarget, action: CardAction, };
