// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardId } from "./BoardId";
import type { UserHandId } from "./UserHandId";
import type { UserMove } from "./UserMove";

export type ClientEvent = "ReciveUserId" | "ReciveBoardId" | { "LoadBoard": BoardId } | { "LoadHand": UserHandId } | { "MakeMove": UserMove };
