// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardId } from "./BoardId";
import type { UserHandId } from "./UserHandId";
import type { UserMove } from "./UserMove";

export type ClientEvent = { "event": "ReciveUserId" } | { "event": "RecivePlayroomId" } | { "event": "LoadBoard", "data": BoardId } | { "event": "LoadHand", "data": UserHandId } | { "event": "MakeMove", "data": UserMove };
