// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { UserHandId } from "./UserHandId";

export type UserHand = { id: UserHandId, available_actions: Array<Action>, };
